#!/bin/sh
#
# srt-compact - Tool to make srt files more compact
#
# Copyright apps.holzheu.de 2023
#
# Usage: cat SRT-FILE | ./src-compact
#
awk '{\
	if ($0 ~ /^[0-9]+$/) { \
		# Counter: Print with leading zeroes \
		printf "%04d ", $0; \
	} else if ($0 ~ /^[0-9]+\:[0-9]+.*/) { \
		# Timestamp: Print only Minutes/Seconds \
		printf "%s ", substr($0, 4, 5); \
	} else if ($0 != "") { \
		# Text \
		printf "%s ",$0; \
	} else { \
		# Empty line \
		print $0; \
	} \
}'
