all:
	analysis Analysis-en.txt -md -url https://youtu.be/VZlg9eeFgiw -t TOC > Analysis-TOC.md
	analysis Analysis-en.txt -md -url https://youtu.be/VZlg9eeFgiw -t CLAIM > Analysis-CLAIM.md
	analysis Analysis-en.txt -md -url https://youtu.be/VZlg9eeFgiw -t WORD > Analysis-WORD.md
	analysis Analysis-en.txt -md -url https://youtu.be/VZlg9eeFgiw -t SAYING > Analysis-SAYING.md
	analysis Analysis-en.txt -md -url https://youtu.be/VZlg9eeFgiw -t DIALECT > Analysis-DIALECT.md
